postgres/postgresql-9.6.10.tar.gz:
  size: 26212016
  object_id: 581f0bec-23b5-48a0-4cfc-b6bc36a023c6
  sha: 10c705ade828c57710ae0f1ad5bf39217765207f
postgres/postgresql-11.9.tar.gz:
  size: 26165850
  object_id: bd709029-0211-4274-7d79-73a80b3fa2bd
  sha: sha256:e98a8649814e2fa632a5d86bfb91f1ad570d47b108bc5c0d0d854803282abb03
