postgres/postgresql-11.22.tar.gz:
  size: 26826810
  object_id: d63d6917-f1f1-4170-6990-bd57514e0cac
  sha: sha256:6445a4e1533c1e8bb616d4a3784bdc4c0226b541f6f0c8d996d9f27d581d49c3
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: 8620e81b-1db3-4bfd-4e14-be10d47e2594
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.14.tar.gz:
  size: 30560938
  object_id: edf36da6-51b7-432f-62ad-30ce76687d7c
  sha: sha256:3bb652690e4a5057a4946b40f494f2f7816a5f83fc34fc7395845c326ded62d2
postgres/postgresql-16.10.tar.gz:
  size: 32861700
  object_id: 2780403c-78a1-4fd8-40f3-1f9504de1126
  sha: sha256:91ede566d6c35db9617a619a5e015c985242144ad27fccae63d11c91cd8c3eed
postgres/postgresql-17.6.tar.gz:
  size: 28141372
  object_id: 43eb1a8b-e66f-4a70-5922-cf2dd3b17766
  sha: sha256:2910b85283674da2dae6ac13fe5ebbaaf3c482446396cba32e6728d3cc736d86
yq/postgres-yq-4.48.1:
  size: 11485368
  object_id: d7dfff4c-388f-4db4-75b8-e0acf99285ee
  sha: sha256:99df6047f5b577a9d25f969f7c3823ada3488de2e2115b30a0abb10d9324fd9f
