postgres/postgresql-11.22.tar.gz:
  size: 26826810
  object_id: d63d6917-f1f1-4170-6990-bd57514e0cac
  sha: sha256:6445a4e1533c1e8bb616d4a3784bdc4c0226b541f6f0c8d996d9f27d581d49c3
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: 8620e81b-1db3-4bfd-4e14-be10d47e2594
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.16.tar.gz:
  size: 30671899
  object_id: 0df172f7-d1b9-42bd-4ee0-8d499573cdcb
  sha: sha256:2de4ea28ee9629d7ced8a0ee264fb6a2f817b082c52aaa281eeef6d95ba73d58
postgres/postgresql-16.12.tar.gz:
  size: 32988804
  object_id: b3d50b66-540f-4c52-5d0c-ba31f689ddfd
  sha: sha256:ced6f95aa2779d7374b68765591c46d692653b2fe3fb5b845de51292f3f83a92
postgres/postgresql-17.7.tar.gz:
  size: 28186920
  object_id: dad6f076-9585-4edd-5e76-154c9a514ee9
  sha: sha256:4a9e94204e265b292b0b36534c38543f24f9d96f5413ceac489ef053082ae752
yq/postgres-yq-4.52.1:
  size: 13627576
  object_id: 5383fbae-206f-4965-6754-2afd2b5c464b
  sha: sha256:bb7c52fbaeec8b208d7eb2e4e782bb56b83fa00b871aa3c7bfd1e33201446e25
