postgres/postgresql-11.22.tar.gz:
  size: 26826810
  object_id: d63d6917-f1f1-4170-6990-bd57514e0cac
  sha: sha256:6445a4e1533c1e8bb616d4a3784bdc4c0226b541f6f0c8d996d9f27d581d49c3
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: 8620e81b-1db3-4bfd-4e14-be10d47e2594
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.15.tar.gz:
  size: 30605101
  object_id: 86743524-3714-4769-63e4-a0ce986013b7
  sha: sha256:c4502ab001cf4385d07f9f2bf40957cd8b81da323f72d6b5918307c8152575f0
postgres/postgresql-16.11.tar.gz:
  size: 32913275
  object_id: b378df80-ffd6-40e5-53c7-7a66d751eb80
  sha: sha256:48c7d6529cad3938af09365c81b9277e8febf1447bd6417efd3533fe4ca8ce3f
postgres/postgresql-17.7.tar.gz:
  size: 28186920
  object_id: dad6f076-9585-4edd-5e76-154c9a514ee9
  sha: sha256:4a9e94204e265b292b0b36534c38543f24f9d96f5413ceac489ef053082ae752
yq/postgres-yq-4.50.1:
  size: 13578424
  object_id: f8acff69-03fd-4947-4e95-057b70ec6e48
  sha: sha256:c7a1278e6bbc4924f41b56db838086c39d13ee25dcb22089e7fbf16ac901f0d4
