postgres/postgresql-11.22.tar.gz:
  size: 26826810
  object_id: d63d6917-f1f1-4170-6990-bd57514e0cac
  sha: sha256:6445a4e1533c1e8bb616d4a3784bdc4c0226b541f6f0c8d996d9f27d581d49c3
postgres/postgresql-13.15.tar.gz:
  size: 28280167
  object_id: b708b6d2-7a7e-4c70-7b52-75a1b7303904
  sha: sha256:28e88226591247ea567ce26c4f5064ae5cc53cba94cb721ab8b6c6adea6218de
postgres/postgresql-15.7.tar.gz:
  size: 30332323
  object_id: ac6ced12-6300-4bcd-56b8-e97892252a2c
  sha: sha256:619541008e4c38560643a5dcfcfca49f39c7ba7f9b11896a88aaa2fd8eb71931
postgres/postgresql-16.3.tar.gz:
  size: 32616059
  object_id: 67d44bf9-7305-445c-524f-64f5c401ce13
  sha: sha256:bd3798c399bc1b6d08b94340f9dd7a75a30a7fa076788ef2f4848be2be6a5fc5
